version: "2"
services:
  whoami:
    image: emilevauge/whoami
    mem_limit: 20m
    restart: always
    ports:
      - "80"
    labels:
     - "traefik.enable=true"
     - "traefik.port=80"
     - "traefik.protocol=http"
     - "traefik.backend=whoami"
     - "traefik.frontend.entryPoints=https"
     - "traefik.frontend.rule=Host: tutum.mytonic.com;PathPrefix: /whoami"
     - "traefik.frontend.redirect.permanent=true"
     - "traefik.frontend.rateLimit.extractorFunc=client.ip"
     - "traefik.frontend.rateLimit.rateSet.whoami.period=10s"
     - "traefik.frontend.rateLimit.rateSet.whoami.average=6"
     - "traefik.frontend.rateLimit.rateSet.whoami.burst=10"
     - "traefik.backend.healthcheck.path=/"
     - "traefik.backend.healthcheck.interval=1s"
     - "traefik.backend.healthcheck.port=80"
     - "traefik.backend.healthcheck.scheme=http"
     - "com.dealer.activate=1"
