defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/ssl/mytonic.crt"
      keyFile = "/etc/ssl/mytonic.key"
  [entryPoints.traefik]
    address = ":9999"
    compress = true

    [entryPoints.traefik.auth.basic]
      users = ["admin:$apr1$nsFFIR1I$PU64nhnMAfKEbiHffpoH11"]
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "mytonic.com"
exposedByDefault = false
watch = true

[api]
dashboard = true
entryPoint = "traefik"
debug = true

# Metrics definition
[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
    buckets = [0.1,0.3,1.2,5.0]
