---
- name: Create directory if not exists
  file: path=/opt/bin state=directory

- name: Copy required file to /opt/bin directory
  template: "src={{ item }}.j2 dest=/opt/bin/{{ item }} mode=0755"
  with_items:
    - "{{ required_files }}"

- name: Copy configuration file to /etc directory
  template: "src=ssh.conf.j2 dest=/etc/ssh.conf mode=0644"

- name: Copy Unit files
  copy: "src={{ item }} dest=/etc/systemd/system/{{ item }} mode=0644"
  with_items:
    - "{{ unit_files }}"
  notify:
    - reload systemd
    - restart import-users service
    - restart import-users timer
